try {
  throw Exception();
} catch(Exception) {
  print "caught";
} finally {
  print "finally.";
}
